```{r}
library(dplyr)
library(survival)
#read data
df<-read.csv("/Users/tianchuhang/Desktop/BS852StatEpi/project/project.2021.csv")

#create two new columns for survival analysis
df$follow_up_year <- df$Age.last.contact - df$Age.enrollment
df <- df %>% mutate(death = ifelse(df$Alive=='Yes', 0, 1))

#median of DSST is 46, so we divide DSST into two parts
df <- df %>% mutate(DSST1 = ifelse(df$DSST >= 46, 1, 0))

head(df)
attach(df)
Surv(follow_up_year, death)~DSST1
#fit a KM curve using all subjects in the lung dataset
km1 <-survfit(Surv(follow_up_year, death)~ DSST1,data=df)
summary(km1)

#Plot KM curves
plot(km1, mark.time=T,col=c("red","black"),  xlab="survival time (days)", ylab="survival probability")
legend("bottomleft",
     c("Low DSST","High DSST"),
     col=c("red","black"), 
     lty=c(1,1))
title(" Kaplan-Meier Curves") 

#logrank test in R
survdiff(Surv(follow_up_year, death)~ DSST1,data=df)
summary(DSST1)
#The log-rank test follows Chi-squared distribution with df=k-1, where k is number of groups. For above example, since p=0.001<0.05, we reject the null hypothesis at alpha=0.05 and conclude that there is significant difference in survival probabilities between men and women during the follow up period.

#create a new data frame called df1 by removing all rows with missing values 
df1 <- df[complete.cases(df), ]
#remove columns with 0 follow up years 
df1 <- df1[df1$follow_up_year!=0 , ]
summary(df1)
df1 <- df1[ which( df1$Alive== 'Yes' |df1$Alive== 'No') , ]

cph <- coxph(Surv(follow_up_year, death)~educ, data=df1)
cph
cph <- coxph(Surv(follow_up_year, death)~sex, data=df1)
cph
cph <- coxph(Surv(follow_up_year, death)~Age.enrollment, data=df1)
cph
cph <- coxph(Surv(follow_up_year, death)~log.il6, data=df1)
cph
cph <- coxph(Surv(follow_up_year, death)~log.new.hscrp, data=df1)
cph
cph <- coxph(Surv(follow_up_year, death)~Z.grip.strength, data=df1)
cph
cph <- coxph(Surv(follow_up_year, death)~Z.bmi, data=df1)
cph
cph <- coxph(Surv(follow_up_year, death)~Z.gait.speed, data=df1)
cph
cph <- coxph(Surv(follow_up_year, death)~Z.fev1.7, data=df1)
cph
cph <- coxph(Surv(follow_up_year, death)~Z.sysbp, data=df1)
cph
summary(df1)
summary(df)
#1868 patients with high dsst
df_high_dsst <- df1[df1$DSST >= 46,]
df_high_dsst
#complement of form 1
summary(df_high_dsst)
sd(df_high_dsst$Age.enrollment)
df_high_dsst[which(df_high_dsst$sex == 2),]
sd(df_high_dsst$educ)
sd(df_high_dsst$log.il6)
sd(df_high_dsst$log.new.hscrp)
sd(df_high_dsst$Z.grip.strength)
sd(df_high_dsst$Z.bmi)
sd(df_high_dsst$Z.gait.speed)
sd(df_high_dsst$Z.fev1.7)
sd(df_high_dsst$Z.sysbp)
#1850patients with low dsst
df_low_dsst <- df1[df1$DSST < 46,]
summary(df_low_dsst)
df_low_dsst[which(df_low_dsst$sex == 2),]
attach(df_low_dsst)
sd(Age.enrollment)
sd(educ)
sd(log.il6)
sd(log.new.hscrp)
sd(Z.grip.strength)
sd(Z.bmi)
sd(Z.gait.speed)
sd(Z.fev1.7)
sd(Z.sysbp)

library(MASS)
cph1 <- stepAIC(update(cph, data=na.omit(df1)),
direction="both") 
#remove missing data before doing AIC selection; otherwise getting an error 
cph1
#Compare Two Cox Models
#perform a likelihood ratio test (LRT) to compare models
anova(cph1,cph)



#heat map
#selected features after step one and only continuous var
df_heat <- df1[,c(1,5,7,8,10,11,12)]
df_heat
#standardization of variables used in cluster analyses
cormat <- round(cor(df_heat),2)
head(cormat)
library(reshape2)
melted_cormat <- melt(cormat)
head(melted_cormat)
library(ggplot2)
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()

# Create a ggheatmap
ggheatmap <- ggplot(melted_cormat, aes(Var2, Var1, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
    name="Pearson\nCorrelation") +
  theme_minimal()+ # minimal theme
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed()
# Add correlation coefficients on the heatmap  
ggheatmap + 
geom_text(aes(Var2, Var1, label = value), color = "black", size = 3) +
theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.grid.major = element_blank(),
  panel.border = element_blank(),
  panel.background = element_blank(),
  axis.ticks = element_blank(),
  legend.justification = c(1, 0),
  legend.position = c(-0.2, 0.2),
  legend.direction = "vertical")+
  guides(fill = guide_colorbar(barwidth = 1, barheight = 7,
                title.position = "top", title.hjust = 0.5))



#crude model
mod1 <- coxph(Surv(follow_up_year, death)~DSST, data=df1)
mod1
summary(mod1)
#adjusted model
cph_adj <- coxph(Surv(follow_up_year, death)~DSST+educ+Age.enrollment+sex+log.il6+log.new.hscrp+Z.gait.speed+Z.fev1.7, data=df1)
summary(cph_adj)

#model selection
library(MASS)
cph_both <- stepAIC(update(cph_adj, data=na.omit(df1)),direction="both")
cph_both
summary(cph_both)
#Compare two cox model
#perform a likelihood ratio test (LRT) to compare models
anova(cph_adj,cph_both)
#The suggests no difference in goodness of fit between the two models (LRT p-value=0.10). Thus we choose the reduced model cph1 with fewer coefficients.

#PH Assumption
cox.zph(cph_both)
#For this example, because the global test p-value =0.055 >0.05, we conclude that the proportional hazard assumption stands.

#adjusted model
cph_str <- coxph(Surv(follow_up_year, death)~DSST+Age.enrollment+strata(sex)+log.il6+Z.gait.speed+Z.fev1.7, data=df1)
cph_str
cox.zph(cph_str)



#goodness of fit
library(pROC)
auc(roc(na.omit(df1)$DSST~predict(cph_both)))
#The AUC=0.8 shows the model fits data well.




cph_backward <- stepAIC(update(cph_adj, data=na.omit(df1)),direction="backward") 
cph_backward
anova(cph_adj,cph_backward)
```
```{r}
#adjusted model
cph_adj <- coxph(Surv(follow_up_year, death)~DSST+educ+Age.enrollment+sex+log.new.hscrp+Z.gait.speed+Z.fev1.7, data=df1)
cph_adj
summary(cph_adj)

#model selection AIC
library(MASS)
cph_both <- stepAIC(update(cph_adj, data=na.omit(df1)),direction="both",k=log(nrow(df1)))
cph_both
summary(cph_both)

#Compare two cox model
#perform a likelihood ratio test (LRT) to compare models
anova(cph_adj,cph_both)
#The suggests no difference in goodness of fit between the two models (LRT p-value=0.10). Thus we choose the reduced model cph1 with fewer coefficients.

#PH Assumption
cox.zph(cph_both)
cox.zph(cph_adj)
#For this example, because the global test p-value =0.072 >0.05, we conclude that the proportional hazard assumption stands.

#adjusted model
cph_str <- coxph(Surv(follow_up_year, death)~DSST+Age.enrollment+strata(sex)+log.new.hscrp+Z.gait.speed+Z.fev1.7, data=df1)
cph_str
cox.zph(cph_str)
```
stepAIC(update(cph_adj, data=na.omit(df1)),direction="both",k=log(nrow(df1)))